MainApp/urls.py
from django.urls import path

from .views import *

app_name = 'MainApp'

urlpatterns = [

    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    # path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('', product_list, name='showcase'),
    path('<str:category_slug>/', product_list, name='product_list'),
    path('<str:category_slug>/<int:id>/', product_detail, name='product_detail'),

]

ToysShop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('shop/', include('MainApp.urls')),
    path('orders/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from django.urls import include
from .views import *


app_name ='orders'

urlpatterns = [

    path('create/', order_create, name='order_create'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from MainApp.models import Product, Category,Customer

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    customer = Customer.objects.get(pk=request.user.pk)
    customer_discount = round(cart.get_total_price() * ((customer.discount)/100))
    order_price = cart.get_total_price() - customer_discount
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'categories': categories,
                                                "order_price": order_price,
                                                "customer_discount": customer_discount})

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr class="border">
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                    <td class="num">{{ item.price }} Руб.</td>
                    <td class="num">{{ item.total_price }} Руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="Discount:">
            <td>Total discount:</td>
            <td colspan="4"></td>
            <td class="num">{{ customer_discount }} Руб.</td>
        </tr>
        <tr class="total">
            <td>Total:</td>
            <td colspan="4"></td>
            <td class="num">{{ order_price }} Руб.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'MainApp:showcase' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>

{% endblock %}