MainApp/urls.py
from django.urls import path

from .views import *

app_name = 'MainApp'

urlpatterns = [

    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    # path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('', product_list, name='showcase'),
    path('<str:category_slug>/', product_list, name='product_list'),
    path('<str:category_slug>/<int:id>/', product_detail, name='product_detail'),

]

ToysShop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('shop/', include('MainApp.urls')),
    path('orders/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

templates/shop/base.html
{% load static %}
{% load bootstrap4 %}


<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% bootstrap_javascript jquery='slim' %}

</head>
<body>
<div class="body">
        <div class="header">
            <div class="container d-flex align-items-center justify-content-center" id="header-row-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row justify-content-center">
                            <img src="{% static 'logo.png' %}">
                        </div>
                    </div>
                </div>
            </div>

            <div class="container bg-light">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="{% url 'MainApp:showcase' %}">Магазин</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Бренды <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Доставка <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Новости <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Контакты <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Сотрудничество <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                        <div class="">
                            {% with total_items=cart|length %}

                                <ul class="navbar-nav mr-auto">
                                    {% if cart|length > 0 %}
                                    <li class="nav-item d-flex justify-content-between align-items-center">
                                        Корзина:
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                                            {{ total_items }} ед.,
                                            {{ cart.get_total_price }}Руб. - {{ user.discount }}%.
                                        </a>
                                    </li>

                                    {% else %}
                                    <li class="nav-item d-flex justify-content-between align-items-center">
                                        Ваша корзина пуста.
                                    </li>
                                    {% endif %}
                                </ul>
                            {% endwith %}
                        </div>
                        <div class="nav-item">
                            <ul class="col nav justify-content-end border">
                                {% if user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                                    href="#" role="button" aria-haspopup="true"
                                    aria-expanded="false">Профиль</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url 'MainApp:profile' %}">Профиль</a>
                                        <a class="dropdown-item" href="{% url 'MainApp:profile_change' %}">
                                        Изменить личные данные</a>
                                        <a class="dropdown-item" href="#">
                                        Изменить пароль</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'MainApp:logout' %}">Выйти</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Удалить</a>
                                    </div>
                                </li>
                                {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'MainApp:register' %}">
                                    Регистрация</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'MainApp:login' %}">
                                    Вход</a></li>
                                {% endif %}
                            </ul>
                        </div>
<!--                    <form class="form-inline my-2 my-lg-0">-->
<!--                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--                    </form>-->
                    </div>
                </nav>

            </div>
        </div>

        <div class="middle border-bottom border-top">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-3 border-right bg-light">
                        {% block sidebar %}
                            <div id="sidebar">
                                <h3>Категории:</h3>
                                <ul class="nav flex-column">
                                    {% for category in categories %}
                                        <li>
                                            <a class="nav-link" href="{% url 'MainApp:product_list' category_slug=category.slug %}">{{ category.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endblock %}
                    </div>
                    <div class="col-8">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

        <div class="footer bg-dark">
            <div class="row">
                <div class="col-12 col-md">
                    <small class="d-block mb-3 text-muted">*for training*  Senchenko Vitali 2020</small>
                </div>
                <div class="col-6 col-md">

                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Новости</a></li>
                        <li><a class="text-muted" href="#">Новинки</a></li>
                        <li><a class="text-muted" href="#">Распродажа</a></li>
                        <li><a class="text-muted" href="#">Контакты</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">

                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Доставка и оплата</a></li>
                        <li><a class="text-muted" href="#">Магазины</a></li>
                        <li><a class="text-muted" href="#">Оптовая продажа</a></li>
                        <li><a class="text-muted" href="#">Карта сайта</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">

                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Лицензия</a></li>
                        <li><a class="text-muted" href="#">Вакансии</a></li>
                        <li><a class="text-muted" href="#">Сотрудничество</a></li>
                        <li><a class="text-muted" href="#">Цели</a></li>
                    </ul>
                </div>
            </div>
        </div>

</div>

</body>
</html>